# Generated by Django 5.1.6 on 2025-04-25 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0002_headteacher_student_headteacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='headteacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='book_store.headteacher'),
            preserve_default=False,
        ),
    ]
