# Generated by Django 5.1.6 on 2025-05-04 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0005_alter_student_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('effective_from', models.DateField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='fee',
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='student',
            name='fee_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='book_store.feestructure'),
        ),
        migrations.DeleteModel(
            name='Fee',
        ),
    ]
